{
    "docs": "https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.10` [[explain](https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html)] failed with 15 errors:", 
            "output": "plugins/action/ix.py:26:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/cliconf/ix.py:33:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/config/interfaces/interfaces.py:14:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/config/l3_interfaces/l3_interfaces.py:13:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/facts/facts.py:5:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/facts/interfaces/interfaces.py:15:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/facts/l3_interfaces/l3_interfaces.py:15:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/ix.py:35:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/module_utils/network/ix/rm_templates/interfaces.py:19:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/modules/ix_command.py:106:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/modules/ix_config.py:229:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'\nplugins/modules/ix_facts.py:91:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon' (at plugins/module_utils/network/ix/facts/facts.py:5:0)\nplugins/modules/ix_interfaces.py:191:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon' (at plugins/module_utils/network/ix/config/interfaces/interfaces.py:14:0)\nplugins/modules/ix_l3_interfaces.py:194:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon' (at plugins/module_utils/network/ix/config/l3_interfaces/l3_interfaces.py:13:0)\nplugins/terminal/ix.py:10:0: traceback: ModuleNotFoundError: No module named 'ansible_collections.ansible.netcommon'"
        }
    ], 
    "verified": false
}
